# Build stage
FROM alpine:3.21 AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . ./
RUN go build -o main .

# Run stage
FROM alpine

WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]
